package email

import (
	"fmt"
	"strings"
)

func GetEmails(building string) *map[string][]string {

	result := make(map[string][]string)

	switch strings.ToLower(building) {
	case "gpr":
		result = map[string][]string{
			"101":  {"wabrenneisen@yahoo.com"},
			"102":  {"viochz@gmail.com"},
			"103":  {"jlaldana.cajas92@gmail.com"},
			"104":  {"juabelco@hotmail.com"},
			"201":  {"KNPQ03@HOTMAIL.COM"},
			"202":  {"ysabelveliz@gmail.com"},
			"203":  {"MNUSLE1@GMAIL.COM"},
			"204":  {"Sccp.pcnapan@gmail.com"},
			"205":  {"JENNYEYEREN@GMAIL.COM"},
			"206":  {"lirarosanna@gmail.com"},
			"207":  {"MIRAP2005@HOTMAIL.COM"},
			"208":  {"hesloyola@gmail.com"},
			"209":  {"rjtorred@gmail.com"},
			"210":  {"dmendoza1183@gmail.com"},
			"211":  {"cfloresv80@gmail.com"},
			"212":  {"lali_aries@hotmail.com"},
			"301":  {"bertliz-1011@hotmail.com"},
			"302":  {"ing_mazg@hotmail.com"},
			"303":  {"ludvi9980@hotmail.com"},
			"304":  {"miluskasambrano537@gmail.com"},
			"305":  {"TATHYVQ_21@HOTMAIL.COM"},
			"306":  {"THALIACHANA590@GMAIL.COM"},
			"307":  {"JEANFRANCOLUCA76@GMAIL.COM"},
			"308":  {"JBOLANOSCHOY@GMAIL.COM"},
			"309":  {"jvaluigi@gmail.com"},
			"310":  {"srh249d@hotmail.com"},
			"311":  {"jrivas309@hotmail.com"},
			"312":  {"rbriceno@almeriz.com"},
			"401":  {"ingebruno90@gmail.com"},
			"402":  {"mmorante1761@gmail.com"},
			"403":  {"anibalcarbajal@hotmail.com"},
			"404":  {"mercadogiovanna5@gmail.com"},
			"405":  {"irisr2404@gmail.com"},
			"406":  {"jmartinezc93@outlook.com"},
			"408":  {"gerssonpipe@hotmail.com"},
			"409":  {"francisl104@yahoo.es"},
			"410":  {"luis.alva2203@gmail.com"},
			"411":  {"ANGGELAMCJ@GMAIL.COM"},
			"412":  {"DAVIDJOSUEDEXTREMORENO@GMAIL.COM"},
			"501":  {"kiara.piscoya@gmail.com"},
			"502":  {"wbances_78@hotmail.com"},
			"503":  {"neyrakamila@gmail.com"},
			"504":  {"MELISSA_1983_36@HOTMAIL.COM"},
			"505":  {"EYESU736@GMAIL.COM"},
			"506":  {"HECTORPAITAMALALOPEZ1986@GMAIL.COM"},
			"507":  {"mariafernanda.primo@gmail.com"},
			"508":  {"GTORIBIOH2013@GMAIL.COM"},
			"509":  {"VICTOR@ARQUITECTOS-WC.COM"},
			"510":  {"mariapia2205@hotmail.com"},
			"511":  {"angelaferreccio16@hotmail.com"},
			"512":  {"YAQUI2400@GMAIL.COM"},
			"601":  {"chavezsilvacristian@gmail.com"},
			"602":  {"COFRADPERU_VENTAS@HOTMAIL.COM"},
			"603":  {"estefaniatm1995@gmail.com"},
			"604":  {"JOSE.GAMARRA@YAHOO.ES"},
			"605":  {"rincon_santiago@hotmail.com"},
			"606":  {"ABEL.VILLANUEVA@GMAIL.COM"},
			"607":  {"jolupoma.01@gmail.com"},
			"608":  {"carruillo@gmail.com"},
			"609":  {"BRYANCABRERACHAVARRY@GMAIL.COM"},
			"610":  {"peter_mil@hotmail.com"},
			"611":  {"adranick96@gmail.com"},
			"612":  {"rutyreyes2@gmail.com"},
			"701":  {"GREGORYHUERTA@GMAIL.COM"},
			"702":  {"DAVIDPADILLACR31@GMAIL.COM"},
			"703":  {"anthony_pp06@hotmail.com"},
			"704":  {"MARYELE77@HOTMAIL.COM"},
			"705":  {"guilleseminario@hotmail.com"},
			"706":  {"ATELLOD@OUTLOOK.ES"},
			"707":  {"mghhmc@hotmail.com"},
			"708":  {"JCPURIZACA33@GMAIL.COM"},
			"709":  {"ashley.martinezmota@gmail.com"},
			"710":  {"vergara.padilla.christian@gmail.com"},
			"711":  {"macoca1977@gmail.com"},
			"712":  {"chars.alex@gmail.com"},
			"801":  {"rosina106@hotmail.com"},
			"802":  {"MAJJINK@GMAIL.COM"},
			"803":  {"yayju0221@hotmail.com"},
			"804":  {"aroneamanda7@gmail.com"},
			"805":  {"siblings.contabilidad@gmail.com"},
			"806":  {"ANA.LM40@GMAIL.COM"},
			"807":  {"KEFIO88@GMAIL.COM"},
			"808":  {"PHILARIOF@GMAIL.COM"},
			"809":  {"jrojasbismarck@gmail.com"},
			"810":  {"LISSET_VERO@HOTMAIL.COM"},
			"811":  {"asesoria.areano@gmail.com"},
			"812":  {"JAIR.CUNZA.SANCHEZ@GMAIL.COM"},
			"901":  {"ABY_28SLC@HOTMAIL.COM"},
			"902":  {"sesmoisolano@gmail.com"},
			"903":  {"CARMENVELAZQUES23@GMAIL.COM"},
			"904":  {"ltarmenod@gmail.com"},
			"905":  {"ABEL.F23@GMAIL.COM"},
			"906":  {"mercedes.siuse.c@gmail.com"},
			"907":  {"acorrales@enfoquetributario.com"},
			"908":  {"gabriela.vasquez.a@gmail.com"},
			"909":  {"dennis.nanahuari@unmsm.edu.pe"},
			"910":  {"MORILLOAR@HOTMAIL.COM"},
			"911":  {"eliofloresbcp@gmail.com"},
			"912":  {"LESLY242@HOTMAIL.COM"},
			"1001": {"JAVIERSM1402@HOTMAIL.COM"},
			"1002": {"ventasimportacionesmhidas@gmail.com"},
			"1003": {"victorgonzales14@hotmail.com"},
			"1004": {"DIANA.NAUPA.CONGACHI@GMAIL.COM"},
			"1005": {"WCARDENAS@GRUPOGSS.COM"},
			"1006": {"RPANIURA@GRUPOCOINP.COM"},
			"1007": {"INVANY007@GMAIL.COM"},
			"1008": {"yuricopa@hotmail.com"},
			"1009": {"sandrasara41@hotmail.com"},
			"1010": {"LARMAS1224@GMAIL.COM"},
			"1011": {"morillor3009@gmail.com"},
			"1012": {"MILI_121088@HOTMAIL.COM"},
			"1101": {"chiroquecalderon@gmail.com"},
			"1102": {"anthonyrb2@gmail.com"},
			"1103": {"INGENIA-LAY@HOTMAIL.COM"},
			"1104": {"JANTONIO.YACOLCA@GMAIL.COM"},
			"1105": {"xabel17@icloud.com"},
			"1106": {"sakaryk@gmail.com"},
			"1107": {"llantu_101@hotmail.com"},
			"1108": {"AMARILIA15@HOTMAIL.COM"},
			"1109": {"XTHIAN86@GMAIL.COM"},
			"1110": {"NHUAMANI@BANBIF.COM.PE"},
			"1111": {"serviciosgeneralesmpm@gmail.com"},
			"1112": {"MTDBV.217@GMAIL.COM"},
			"1201": {"mercedesqc81@hotmail.com"},
			"1202": {"lihumi6000@hotmail.com"},
			"1203": {"MARITZA.CHE91@GMAIL.COM"},
			"1204": {"MARYCELSA_ES@HOTMAIL.COM"},
			"1205": {"edmagtell@gmail.com"},
			"1206": {"brisitaqs@gmail.com"},
			"1207": {"JCPLASENCIAL@GMAIL.COM"},
			"1208": {"serp1803@gmail.com"},
			"1209": {"moralesbarrerajenny13@gmail.com"},
			"1210": {"JUANCMZ1995@GMAIL.COM"},
			"1211": {"JOSEMEDINAFLORES@GMAIL.COM"},
			"1212": {"OMARDIOSES@HOTMAIL.COM"},
			"1301": {"nataliepatricia088@gmail.com"},
			"1302": {"charlesalfa11@gmail.com"},
			"1303": {"pilar_silviaa@hotmail.com"},
			"1304": {"CELEZAMA@GMAIL.COM"},
			"1305": {"kristiangcd257@gmail.com"},
			"1306": {"ddonayres@hotmail.com"},
			"1307": {"daniel.ca180987@gmail.com"},
			"1308": {"aysr1807@gmail.com"},
			"1309": {"HIDESROJASH@GMAIL.COM"},
			"1310": {"alebry18@gmail.com"},
			"1311": {"ruthmar2203@hotmail.com"},
			"1312": {"cesar.hoyos.n@gmail.com"},
			"1401": {"JORGE.CHAUCAT@GMAIL.COM"},
			"1402": {"erikpapa@gmail.com"},
			"1403": {"saul_huallanca_velasquez@hotmail.com"},
			"1404": {"ilianafuentesr@gmail.com", "cpalma@pucp.pe"},
			"1405": {"juancarlos_urquiaga@hotmail.com"},
			"1406": {"mavo62@gmail.com"},
			"1407": {"edwinzn_dream@hotmail.com"},
			"1408": {"ALOPEZV@TOTTUS.COM.PE"},
			"1409": {"danielsecond@hotmail.com"},
			"1410": {"CAROLINA_TAVARA@HOTMAIL.COM"},
			"1411": {"joel_rueda13@hotmail.com"},
			"1412": {"chrissie.economic@gmail.com"},
			"1501": {"BLANKFARMA@HOTMAIL.COM"},
			"1502": {"MARCX_@HOTMAIL.COM"},
			"1503": {"junior.sancho14@hotmail.com"},
			"1504": {"AILED.LORENA@GMAIL.COM"},
			"1505": {"GRECIA.2409.93@GMAIL.COM"},
			"1506": {"kpriale21@gmail.com"},
			"1507": {"saragosa_14_1991@hotmail.com"},
			"1508": {"cesar.panduro@hotmail.com"},
			"1509": {"palas.13@gmail.com"},
			"1510": {"yohana_252@hotmail.com"},
			"1511": {"ramirezc.pilar@gmail.com"},
			"1512": {"LUISDONAYREMS@GMAIL.COM"},
			"1601": {"djulio_g@hotmail.com"},
			"1602": {"fictor1@hotmail.com"},
			"1603": {"luiscasas@hotmail.es"},
			"1604": {"donayre.lucy@gmail.com"},
			"1605": {"ABORJASFELIX@GMAIL.COM"},
			"1606": {"Rriverach1804@gmail.com"},
			"1607": {"elvisv20@hotmail.com"},
			"1608": {"JOSE_C_CA@HOTMAIL.COM"},
			"1609": {"erickskd8d@gmail.com"},
			"1610": {"FIORELOM@GMAIL.COM"},
			"1611": {"grey.cruzado@gmail.com"},
			"1612": {"luceroupc@gmail.com"},
			"1701": {"jzelayad@hotmail.com"},
			"1702": {"albertochouregal@gmail.com"},
			"1703": {"KHAROLSALINAS@GMAIL.COM"},
			"1704": {"pnichodc@mpfn.gob.pe"},
			"1705": {"JUANANTON86@HOTMAIL.COM"},
			"1706": {"tino.agurtob@gmail.com"},
			"1707": {"aragonjohanaisa@gmail.com"},
			"1708": {"fabiola.alburqueque@gmail.com"},
			"1709": {"LISBETH.MORALESLAV@GMAIL.COM"},
			"1710": {"KNAUPAM@GMAIL.COM"},
			"1711": {"cuyutupa.jorge@gmail.com"},
			"1712": {"angelo.ponceh@gmail.com"},
			"1801": {"lalvarez.aguayo84@gmail.com"},
			"1802": {"JERNAUH@GMAIL.COM"},
			"1803": {"jjmanchego@gmail.com"},
			"1804": {"aiquipaadrian@gmail.com"},
			"1805": {"MARINOLI23@GMAIL.COM"},
			"1806": {"claheal5@gmail.com"},
			"1807": {"newmoon798@gmail.com"},
			"1808": {"giullianolanda@gmail.com"},
			"1809": {"BRUCE.CHIRINOS.BARRERA@GMAIL.COM"},
			"1810": {"Kamezamo@hotmail.com"},
			"1811": {"demirel.tuse@ferreyros.com.pe"},
			"1812": {"LUCYMAR0312@HOTMAIL.COM"},
			"1901": {"maritza.maribella@hotmail.com"},
			"1902": {"sheilatafur2015@gmail.com"},
			"1903": {"graciela.torresfuentes@gmail.com"},
			"1904": {"oscar.floresvaldez@gmail.com"},
			"1905": {"HINOJOSAFLORESMAYRA@GMAIL.COM"},
			"1906": {"AILQUIMICHE@CPSAA.COM.PE"},
			"1907": {"patriciaromero060584@gmail.com"},
			"1908": {"STN.PMANAGER@GMAIL.COM"},
			"1909": {"lchampi@hotmail.com"},
			"1910": {"MACCHIAVELLO.EDUARDO@GMAIL.COM"},
			"1911": {"romerogonzalesc@gmail.com"},
			"1912": {"javierqg.25@gmail.com"},
		}

	case "belmonte":
		result = map[string][]string{
			"101": {"nitziarojas@yahoo.es", ""},
			"102": {"yadira.lopez@unmsm.edu.pe", "angeles.19@icloud.com"},
			"103": {"crubinosc@gmail.com", ""},
			"104": {"petipaf@hotmail.com", ""},
			"201": {"marisollocatelli@yahoo.com", ""},
			"202": {"juliocbc73@hotmail.com", ""},
			"203": {"luzmari67@hotmail.com", ""},
			"204": {"ctoranzo7@gmail.com", ""},
			"301": {"wzegarrah@gmail.com", ""},
			"302": {"ginajacintoher@hotmail.com", ""},
			"303": {"batallanosmargot@gmail.com", ""},
			"304": {"yulichu46@gmail.com", ""},
			"401": {"jchiraf@hotmail.com", ""},
			"402": {"maketa3@hotmail.com", ""},
			"403": {"martinalache@gmail.com", ""},
			"404": {"giorellyguibovich@gmail.com", ""},
			"501": {"hmoragonzales@gmail.com", ""},
			"502": {"vic_bam85@hotmail.com", ""},
			"503": {"vivancoantoniop@gmail.com", ""},
			"504": {"betopanduro@gmail.com", ""},
			"601": {"endovascularsolis@gmail.com", ""},
			"602": {"dante.benites@newmont.com", ""},
			"603": {"frankperezlamas@gmail.com", ""},
			"604": {"estebanjenny202@gmail.com", ""},
		}
	case "torrereal":
		result = map[string][]string{
			"101": {"brumi02@gmail.com", ""},
			"102": {"carmendavilarioja@gmail.com", ""},
			"103": {"hiroshi.miranda@gmail.com", ""},
			"201": {"rubirojasz@gmail.com", ""},
			"203": {"lilianadv1707@gmail.com", ""},
			"204": {"miralvant24@gmail.com", ""},
			"301": {"jaymefloresr1973@yahoo.com", ""},
			"302": {"percy.huaylinos@pucp.pe", ""},
			"303": {"kjauregui@esan.edu.pe", ""},
			"304": {"norbertosoza_67@hotmail.com", ""},
			"401": {"vicky.victorino@gmail.com", ""},
			"402": {"fort.jeanpierre@outlook.com", "daniella.vargas@outlook.com"},
			"403": {"lulurose4020@gmail.com", ""},
			"404": {"mariela.noles@gmail.com", ""},
			"501": {"cintia.lz28@hotmail.com", ""},
			"502": {"angizita@hotmail.com", ""},
			"503": {"jvagiles@gmail.com", ""},
			"504": {"emamansilla11@gmail.com", ""},
			"601": {"carmen_c15@hotmail.com", ""},
			"603": {"maribeltipa2018@gmail.com", ""},
			"604": {"adagabygarcia@yahoo.com", ""},
			"701": {"rocioplc@hotmail.com", ""},
			"702": {"tomas.sanchez@spital.so.ch", ""},
			"703": {"Rosa.caballeroacevedo@gmail.com", ""},
			"704": {"mariela.noles@gmail.com", ""},
			"801": {"juliotakimoto@hotmail.com", ""},
			"802": {"laura.abogados3@gmail.com", ""},
			"803": {"kattye.montenegro@gmail.com", ""},
			"804": {"medithsol@gmail.com", ""},
			"0":   {"jsanchezb.uni@gmail.com", ""},
			"1":   {"magda_rivas@yahoo.com", ""},
			"2":   {"mariela.noles@gmail.com", ""},
			"3":   {"allisonalfarorobledo@hotmail.com", ""},
		}
	case "mirador":
		result = map[string][]string{
			"101": {"dcruzado2000@yahoo.es"},
			"201": {"vferiasmg@gmail.com"},
			"202": {"jreategui33@hotmail.com"},
			"301": {"carina-blasm@hotmail.com"},
			"302": {"mariana.bauer@icloud.com"},
			"401": {"leoch1305@gmail.com"},
			"402": {"ariana.soy@hotmail.com"},
			"501": {"sanchezpoma.richard@gmail.com"},
			"502": {"mreategui@intercorp.com.pe"},
			"601": {"rosacaceda10@gmail.com"},
			"602": {"angelcop1926@gmail.com"},
			"701": {"gcerda068@gmail.com"},
			"702": {"jonathan_fabris@yahoo.com"},
			"703": {"jordi.rib.hib@gmail.com"},
		}
	case "nitoa":
		result = map[string][]string{
			"101": {"", ""},
			"102": {"", ""},
			"103": {"", ""},
			"104": {"", ""},
			"201": {"", ""},
			"202": {"", ""},
			"203": {"", ""},
			"204": {"", ""},
			"301": {"", ""},
			"302": {"", ""},
			"303": {"", ""},
			"304": {"", ""},
			"401": {"", ""},
			"402": {"", ""},
			"403": {"", ""},
			"404": {"", ""},
			"501": {"", ""},
			"502": {"Carranzamaria055@gmail.com", ""},
			"503": {"Yoan.katherine@gmail.com", ""},
			"504": {"jlluperdi@gmail.com", ""},
			"601": {"", ""},
			"602": {"nati.028@hotmail.com", ""},
			"603": {"mirko.daga21@gmail.com", ""},
			"604": {"", ""},
			"701": {"analuciaterrones@outlook.com", ""},
			"702": {"leila_ber87@hotmail.com", ""},
			"703": {"Jessica.delvalle.cardenas@gmail.com", ""},
			"704": {"eduardo.araoz@hotmail.com", ""},
			"801": {"inesvime@gmail.com", ""},
			"802": {"jjtellom@gmail.com", ""},
			"803": {"pamela.val.gon@gmail.com", ""},
			"804": {"gabrielavegamaggiorini3@gmail.com", ""},
			"902": {"", ""},
			"903": {"jfa0688@gmail.com", ""},
			"904": {"aileen.aguero@gmail.com", ""},
		}
	case "valera":
		result = map[string][]string{
			"101": {"stpame_@hotmail.com", ""},
			"102": {"dvallejos09@gmail.com", ""},
			"103": {"henrryacuare@swsport.com", ""},
			"201": {"delia_chaca@hotmail.com", ""},
			"202": {"ojedaronal1985@gmail.com", ""},
			"203": {"henriquez.james@gmail.com", ""},
			"204": {"alexnreaup@volut.es", "clorylas@hotmail.com"},
			"301": {"lmuancasv@hotmail.com", "ronweld@hotmail.com"},
			"302": {"mariahenriemodelarosa@gmail.com", ""},
			"303": {"monicust@hotmail.com", ""},
			"304": {"clazarte@gmail.com", ""},
			"401": {"fprafaele23@gmail.com", ""},
			"402": {"lucelita@hotmail.com", ""},
			"403": {"jonathanwe@gmail.com", ""},
			"404": {"christian.moscoso@pe.g4s.com", ""},
			"501": {"danielvaldezrodriguez@gmail.com", ""},
			"502": {"", ""},
			"503": {"mhuancasv@gmail.com", ""},
			"504": {"csiguas20@gmail.com", ""},
			"601": {"jhegonzam@motra.com", "copypackar@hotmail.com"},
			"602": {"febdesmonicabrea@gmail.com", ""},
			"603": {"sheguidc_27@hotmail.com", ""},
			"604": {"edwardchacon7@gmail.com", ""},
		}
	case "golf":
		result = map[string][]string{
			"202": {"pamella.phang@gmail.com", "ecrosato1@gmail.com"},
			"203": {"marice_pilates@hotmail.com", ""},
			"204": {"hermannezcurra@hotmail.com", "dennissecug@gmail.com"},
			"205": {"enrique.pareja@labofta.com", "milagros.luperdi@labofta.com"},
			"301": {"cfreundt1932@hotmail.com", ""},
			"401": {"finanzas@corplastperu.com", "gerencia@corplastperu.com"},
			"402": {"jabramitri@hotmail.com", ""},
			"501": {"luis.terranova@hotmail.com", "chiarapg19@gmail.com"},
			"503": {"ximenamuro@hotmail.com", "erickfreundt@hotmail.com"},
			"504": {"jessicamuro@hotmail.com", ""},
			"506": {"olenkanr@hotmail.com", "danielgonzalesm1@hotmail.com"},
			"601": {"patibuse@gmail.com", "aballon@sacro.net"},
			"603": {"cabusabbah@gmail.com", "claudiamannucci@hotmail.com"},
			"604": {"claudia_silvalolas@yahoo.com", "rodrigoZavalaF@pacifico.com.pe"},
			"605": {"comercial@lizini.com", ""},
			"606": {"comercial@lizini.com", ""},
			"701": {"palomadelgado@hotmail.com", ""},
			"702": {"renata.maciel.silveira@gmail.com", "ernestogq@yahoo.com"},
			"703": {"verosoul1980@gmail.com", ""},
			"704": {"limafmobuildings@state.gov", "alfredolabrousse@gmail.com"},
			"705": {"comercial@lizini.com", ""},
			"706": {"comercial@lizini.com", ""},
			"801": {"carloschang1950@gmail.com", "sadithdc@gmail.com"},
			"803": {"raqui_12@hotmail.com", ""},
			"804": {"finanzas@corplastperu.com", "import@corplastperu.com"},
			"805": {"aleregalado@yahoo.com", ""},
			"901": {"luis10_340@hotmail.com", "epoblete@gmail.com"},
			"41":  {"comercial@lizini.com", ""},
			"42":  {"comercial@lizini.com", ""},
			"43":  {"comercial@lizini.com", ""},
			"44":  {"comercial@lizini.com", ""},
			"45":  {"comercial@lizini.com", ""},
			"46":  {"comercial@lizini.com", ""},
			"47":  {"comercial@lizini.com", ""},
			"48":  {"comercial@lizini.com", ""},
			"56":  {"comercial@lizini.com", ""},
			"57":  {"comercial@lizini.com", ""},
			"58":  {"comercial@lizini.com", ""},
			"61":  {"comercial@lizini.com", ""},
			"62":  {"comercial@lizini.com", ""},
			"63":  {"comercial@lizini.com", ""},
			"64":  {"comercial@lizini.com", ""},
			"65":  {"comercial@lizini.com", ""},
			"66":  {"comercial@lizini.com", ""},
			"13":  {"comercial@lizini.com", ""},
		}
	case "mora":
		result = map[string][]string{
			"101": {"ybenzaquen@gmail.com", ""},
			"102": {"natalyudm@gmail.com", ""},
			"103": {"medina.gironzini@gmail.com", ""},
			"201": {"alvaro.cordova.flores@hotmail.com", "laura.dehaibi@gmail.com"},
			"202": {"waltertlh@hotmail.com", ""},
			"203": {"eruizf21@gmail.com", ""},
			"204": {"marthadiestra7@gmail.com", ""},
			"301": {"nira.florian2011@gmail.com", ""},
			"302": {"anajovet@hotmail.com", ""},
			"303": {"ivsuli3@gmail.com", ""},
			"304": {"macarrascoa@gmail.com", ""},
			"401": {"soresttes@gmail.com", ""},
			"402": {"mdiaz@techint.com", ""},
			"403": {"parrawong@gmail.com", ""},
			"404": {"lizardo.aguilar@ferreyros.com.pe", ""},
			"501": {"parrawongr@gmail.com", ""},
			"502": {"pilarmarquezc@hotmail.com", "yagnir22@gmail.com"},
			"503": {"ivsuli3@gmail.com", ""},
			"504": {"renattomaselli@icloud.com", ""},
			"601": {"isabel.raez.c@gmail.com", ""},
			"602": {"mcueva1610@gmail.com", ""},
			"603": {"nicole.eb3@gmail.com", ""},
			"604": {"camila.bonilla.buendia@gmail.com", ""},
			"701": {"victor.mbm@gmail.com", ""},
			"702": {"lissette.ramirez26@hotmail.com", ""},
			"703": {"gourmet-catering@hotmail.com", ""},
			"704": {"pilarmarquezc@hotmail.com", "yagnir22@gmail.com"},
		}
	case "alayza":
		result = map[string][]string{
			"101": {"maritep@yahoo.com", ""},
			"102": {"nelidamf@hotmail.com", "marcoestradamier@hotmail.com"},
			"103": {"ozonomasvida.2015@gmail.com", "michel_valcruz@hotmail.com"},
			"104": {"rzegarraacuna@gmail.com", ""},
			"201": {"piamarroquin@hotmail.com", ""},
			"202": {"lesliemaromo22@gmail.com", "wildemendoza@gmail.com"},
			"203": {"kvv_021@hotmail.com", ""},
			"204": {"max_lopezpinto@hotmail.com", "yolyviruska@hotmail.com"},
			"301": {"nmicalay@gmail.com", ""},
			"302": {"csolisva0169@gmail.com", ""},
			"303": {"cristinavargas26@gmail.com", "yess_vargh@hotmail.com"},
			"304": {"fzm_lawyer_peru@hotmail.com", "mvr@zunigavelasquezabogados.com"},
			"401": {"dosalvatierra@gmail.com", "paulateresa20@hotmail.com"},
			"402": {"dyana.alegre@gmail.com", "victorequena71080@gmail.com"},
			"403": {"kacuto@hotmail.com", ""},
			"404": {"ivdmb2020@gmail.com", ""},
			"501": {"edgard.leon29@gmail.com", "vaneinfantas29@gmail.com"},
			"502": {"cococd1@hotmail.com", "ni1910@hotmail.com"},
			"503": {"valvarez.al@gmail.com", ""},
			"504": {"manuel.alejandro83@gmail.com", ""},
			"601": {"arq_will@hotmail.com", "wan-927@hotmail.com "},
			"602": {"kticona@gmail.com", ""},
			"603": {"henrylicam@gmail.com", ""},
			"604": {"mabelmf_47@hotmail.com", ""},
			"701": {"psagasteguia@yahoo.com", ""},
			"702": {"jaulin94@gmail.com", ""},
			"703": {"mangela1001@gmail.com", ""},
			"704": {"maryellen.reategui@gmail.com", "andreujorge130153@gmail.com"},
			"801": {"lbello.ucv@gmail.com", ""},
			"802": {"maeutamayo@gmail.com", ""},
			"803": {"", ""},
		}
	case "sbs":
		result = map[string][]string{
			"101": {"", ""},
			"201": {"helgariega@hotmail.com", ""},
			"202": {"abelalonsofeb@gmail.com", ""},
			"301": {"adolfomoran6@hotmail.com", ""},
			"302": {"aracellipalomino01@gmail.com", ""},
			"401": {"patriciamhernandez@hotmail.com", ""},
			"402": {"ruthayalaochoa@gmail.com", ""},
			"501": {"elizabethpun3@gmail.com", ""},
			"502": {"crozas64@hotmail.com", ""},
			"601": {"", ""},
		}
	}
	return &result
}

func ValidateEmails(number, building string) string {
	allEmails := *GetEmails(building)

	if len(allEmails[number]) == 0 {
		fmt.Printf("Apartment %v dont have an email", number)
		return number
	}

	return ""
}
